# dependabot proxy for automatic version scanning

FROM nginx:1.25

FROM portainer/portainer-ce:linux-amd64-2.18.3

FROM dpage/pgadmin4:7.3

FROM postgres:15.3

# TODO: for some reason ignored by dependabot...
FROM minio/minio:RELEASE.2023-06-19T19-52-50Z

FROM mdernovoi/mlflow:v1.5.0

FROM gitlab/gitlab-ce:16.1.0-ce.0

FROM gitlab/gitlab-runner:ubuntu-v16.1.0
