# dependabot proxy for automatic version scanning

FROM nginx:1.24

FROM portainer/portainer-ce:linux-amd64-2.18.2

FROM dpage/pgadmin4:7.1

FROM postgres:15.3

# TODO: for some reason ignored by dependabot...
FROM minio/minio:RELEASE.2023-04-20T17-56-55Z

FROM mdernovoi/mlflow:v1.4.0

FROM gitlab/gitlab-ce:15.11.3-ce.0

FROM gitlab/gitlab-runner:ubuntu-v15.11.0

FROm ghcr.io/mlflow/mlflow:v2.3.1