
site_name: Data Analysis Platform 

repo_url: https://github.com/mdernovoi/data-analysis-platform
repo_name: 'GitHub'

docs_dir: docs

theme: readthedocs


#plugins:
#  - search  # To have search functionality on the document
#  - mkdocstrings  # To generate documentation from the code docstrings

pages:
  - Home: index.md
