
site_name: Data Analysis Platform 
site_description: A powerful and versatile data analysis platform infrastructure framework.
site_author: Maxim Dernovoi

repo_url: https://github.com/mdernovoi/data-analysis-platform
repo_name: 'mdernovoi/data-analysis-platform'

docs_dir: docs

theme: readthedocs
lang: en

markdown_extensions:
  toc:
    permalink: True

plugins:
  search:
    indexing: 'full'

#plugins:
#  - search  # To have search functionality on the document
#  - mkdocstrings  # To generate documentation from the code docstrings

nav:
  - Home: index.md
  - Architecture and Concepts: architecture.md
  - Getting Started:
    - Installation: provision.md
    - TLS Security: tls.md
    - Customization: customization.md
    - Version Upgrade: upgrade.md
  - Development environments: environments.md
  - Dev notes: developer.md
