
site_name: Data Analysis Platform 
site_description: A powerful and versatile data analysis platform infrastructure framework.
site_author: Maxim Dernovoi

repo_url: https://github.com/mdernovoi/data-analysis-platform
repo_name: 'mdernovoi/data-analysis-platform'

docs_dir: docs

theme: readthedocs


#plugins:
#  - search  # To have search functionality on the document
#  - mkdocstrings  # To generate documentation from the code docstrings

nav:
    - Home: index.md
    - Architecture and Concepts: architecture.md
    - Installation: provision.md
        - TLS security: tls.md
        - Customization: customization.md
        - Upgrade: upgrade.md
    - Development environments: environments.md
    - Dev notes: developer.md
