

stages:
  - build_dev_base
  - build_dev_base_children

build_dev-base:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  stage: build_dev_base
  interruptible: true
  rules:
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
      changes:
        - dev-base/*
  variables:
    IMAGE_NAME: "dev-base"
    WORKING_DIR: "dev-base"
  after_script:
    - /bin/sh build_scripts/after-docker-build.sh $IMAGE_NAME
  script:
    # copy secrets from GitLab to local file system
    - cp $authorized_keys secrets/authorized_keys
    - cp $ssh_host_rsa_key secrets/ssh_host_rsa_key
    - cp $ssh_host_rsa_key_pub secrets/ssh_host_rsa_key.pub
    # prepare build environment
    - /bin/sh build_scripts/before-docker-build.sh $IMAGE_NAME
    # build Docker image
    - /kaniko/executor
      --context "${WORKING_DIR}"
      --dockerfile "${WORKING_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$IMAGE_NAME:${CI_COMMIT_TAG}"
  
build_dev-python-r:
  image:
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  stage: build_dev_base_children
  interruptible: true
  rules:
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
      changes:
        - dev-python-r/*
        - dev-base/*
  variables:
    IMAGE_NAME: "dev-python-r"
    WORKING_DIR: "dev-python-r"
  after_script:
    - /bin/sh build_scripts/after-docker-build.sh $IMAGE_NAME
  script:
    # copy secrets from GitLab to local file system
    - cp $jupyter_notebook_password_txt secrets/jupyter_notebook_password.txt
    # prepare build environment
    - /bin/sh build_scripts/before-docker-build.sh $IMAGE_NAME
    # build Docker image
    - /kaniko/executor
      --context "${WORKING_DIR}"
      --dockerfile "${WORKING_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$IMAGE_NAME:${CI_COMMIT_TAG}"




