---
# tasks file for role_docker

### Install latest docker
- name: Install docker dependencies
  package:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    
- name: Add Docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  package:
    name: 
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
    state: present

- name: Add infrastructure account to docker group
  ansible.builtin.user:
    name: "{{ infrastructure_account.user }}"
    groups: docker
    append: yes

